### ISSUE TITLE
traceback when running openqa-review --help on Tumbleweed

### ISSUE THREAD

**Issue by vpelcak** [okurz/openqa_review#57] opened 2017-02-08 16:10 UTC
> openqa-review --help
Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2991, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 662, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 970, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 856, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'configparser' distribution was not found and is required by openqa-review

**Comment by okurz** [comment] 2017-02-09 06:37
duplicate of #56 but thank you for reporting it.

**Closed by okurz** 2017-02-09 06:37 UTC
